---
- name: Create an 4096 bit Key and store it in Vault
  hosts: localhost
  gather_facts: false 
  vars:
    secret_name: "test-right-now4"
#
#
    vault_url: "https://vault.theglens.net:8200"
    vault_mount: "kv"
  
  tasks:
   - name: print a message
     ansible.builtin.debug:
       msg: "v2.2"

   - name: 01 - Generate the Private Key
     community.crypto.openssl_privatekey:
       type: RSA
       size: 4096
       path: "private.key"


   - name: 02 - Extract the Public Key
     community.crypto.openssl_publickey:
       path: "public.key"
       privatekey_path: "private.key"


   - name: Create a new secret and store the two keys
     community.hashi_vault.vault_kv2_write:
       url: "https://vault.theglens.net:8200"
       path: "{{ secret_name }}"
       auth_method: token
       token: "{{ ansible_password }}"
       engine_mount_point: "kv"
       data: 
         public_key: "{{ lookup('file', 'public.key') }}"
         private_key: "{{ lookup('file', 'private.key') }}"


