---
- name: Create an EC384 Key and store it in Vault
  hosts: localhost
  gather_facts: false
  
  tasks:
   - name: print a message
     ansible.builtin.debug:
       msg: "v2.3"

   - name: 01 - Create a new Elliptic Curve Key Pair
     community.crypto.openssl_privatekey:
       # curve: secp384r1
       curve: "{{ curve }}"
       type: ECC
       path: ~/le_private_key.pem

   - name: 02 - Extract the Public Key
     community.crypto.openssl_publickey:
       path: ~/le_public_key.pem
       privatekey_path: ~/le_private_key.pem


   - name: 03 - Create a new secret and store the two keys
     community.hashi_vault.vault_kv2_write:
       path: "{{ key_name }}"
       url: "{{ vault_url }}"
       auth_method: "{{ vault_auth_method  }}"
       token: "{{ vault_token }}"
       engine_mount_point: "{{ vault_mount }}"
       data:
        public_key: "{{ lookup('file', '~/le_public_key.pem') }}"
        private_key: "{{ lookup('file', '~/le_private_key.pem') }}"
     register: ec_write
