---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost

  vars:
    secret_name: "test-right-now"
#
#
    vault_url: "https://vault.theglens.net:8200"
    vault_mount: "kv"
  
  tasks:
   - name: print a message
     ansible.builtin.debug:
       msg: "v2.0.1"

   - name: 01 - Generate a Private Key for the FQDN
     community.crypto.openssl_privatekey:
       curve: secp384r1
       type: ECC
       path: "private.key"

   - name: 02 - Generate an OpenSSL public key in PEM format
     community.crypto.openssl_publickey:
       path: "public.key"
       privatekey_path: "private.key"


   - name: Create a new Path and two new key-value pairs in the KV2 engine
     community.hashi_vault.vault_kv2_write:
       url: "https://vault.theglens.net:8200"
       path: "secret_name"
       auth_method: token
       token: "{{ ansible_password }}"
       engine_mount_point: "kv"
       data: 
         private_key: "private.key"
         public_key: "public.pub"