---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost

  vars:
    secret_name: "test-ecc384-key"
#
#
    vault_url: "https://vault.theglens.net:8200"
    vault_mount: "kv"
  
  tasks:
   - name: print 
     ansible.builtin.debug:
       msg: "hi there tim1"

   - name: 01 - Generate a Private Key for the FQDN
     community.crypto.openssl_privatekey:
       curve: secp384r1
       type: ECC

   - name: 02 - Generate an OpenSSL public key in PEM format
     community.crypto.openssl_publickey:
       path: "~/{{ secret_name }}.key"
       privatekey_path: "~/{{ secret_name }}.pub"


   - name: Create a new Path and two new key-value pairs in the KV2 engine
     community.hashi_vault.vault_kv2_write:
       url: "https://vault.theglens.net:8200"
       path: "secret_name"
       auth_method: token
       token: "{{ ansible_password }}"
       engine_mount_point: "kv"
       data: 
         private_key: "~/{{ secret_name }}.key"
         public_key: "~/{{ secret_name }}.pub"