---
- name: Create an 4096 bit Key and store it in Vault
  hosts: localhost
  gather_facts: false
  vars:
    vault_url: "https://vault.theglens.net:8200"
    vault_mount: "kv"
  
  tasks:
   - name: print a message
     ansible.builtin.debug:
       msg: "Internal version v3.0"

   - name: 01 - Generate a 4096 bit RSA Private Key
     community.crypto.openssl_privatekey:
       type: RSA
       #size: 4096
       path: ~/le_private_key.pem


   - name: 02 - Extract the Public Key
     community.crypto.openssl_publickey:
       path: ~/le_public_key.pem
       privatekey_path: ~/le_private_key.pem



   - name: 03 - Create a new secret and store the two keys
     community.hashi_vault.vault_kv2_write:
       path: "{{ key_name }}"
       url: "{{ vault_url }}"
       auth_method: "{{ vault_auth_method  }}"
       token: "{{ vault_token }}"
       engine_mount_point: "{{ vault_mount }}"
       data:
        public_key: "{{ lookup('file', '~/le_public_key.pem') }}"
        private_key: "{{ lookup('file', '~/le_private_key.pem') }}"
     register: rsa_write
