---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost
  gather_facts: false
  vars: 
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"
   vault_secret: "le_stage_key/public_key"

  tasks:
    - name: Read The Let's Encrypt Private Key from Vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_url }}"
        engine_mount_point: "{{ vault_mount }}"
        path: "{{ vault_secret }}"
        auth_method: token
        token: "{{ ansible_password }}"
      register: response

    - name: Print the Private Key
      ansible.builtin.debug:
        msg: "{{ response.secret.private_key }}"




    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play



    - name: Create ACME account
      community.crypto.acme_account:
        account_key_src: "~/le-account.key"
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_version: 2
        contact:
          - mailto:timmayglen@gmail.com
        state: present
        terms_agreed: true
      register: acme_account

    - name: Display ACME account details
      ansible.builtin.debug:
        var: acme_account
