---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"
   fqdn: "lab-ftd.theglens.net"
   le_email: "timmayglen@gmail.com"

  tasks:

   - name: Simple A record (IPV4 address) lookup for example.com
     ansible.builtin.debug:
       msg: "{{ lookup('community.general.dig', 'www.cnn.com.')}}"
 

   - name: TIMMAY Stop the Playbool
     ansible.builtin.meta: end_play

