---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Query IP geolocation API using ansible.builtin.uri
      ansible.builtin.uri:
        url: "https://dns.google/resolve?name=ssl-vpn.theglens.net&type=a&do=1"
        method: GET
        return_content: true
      register: dns_result

    - name: Print the geolocation result
      ansible.builtin.debug:
        var: dns_result.content

    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play

