---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Create TXT record with value "unique value"
      community.general.cloudflare_dns:
#        account_api_key: "{{ ansible_password }}"
        api_token: "{{ ansible_password }}"
        account_email: "{{ ansible_user }}"
        record: testansible
        type: A
        value: 2.2.2.2
        state: absent    # present (default), absent
        zone: theglens.net
      register: response

    - name: Debug response
      debug:
        var: response

    - name: Debug task parameters
      debug:
        msg:
          - "account_api_key: {{ ansible_password }}"
          - "account_email: {{ ansible_user }}"
          - "record: testansible"
          - "type: A"
          - "value: 2.2.2.2"
          - "state: present"
          - "zone: theglens.net"