---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"
   fqdn: "lab-ftd.theglens.net"
   le_email: "timmayglen@gmail.com"

  tasks:

   - name: Generate a random 7-character string of lowercase letters
     ansible.builtin.set_fact:
       rand: "{{ lookup('password', '/dev/null', length=7, chars=ascii_lowercase) }}"
       fqdn: "{{ rand }}.theglens.net"


   - name: 01 - Read The TLS Server Private Key from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "{{ fqdn | replace('.', '_') }}_keys"
      auth_method: token
      token: "{{ ansible_password }}"
     register: server_private_key


   - name: 02 - Read The Let's Encrypt Private Key from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "le_stage_key"   # options: le_stage_key, le_prod_key
      auth_method: token
      token: "{{ ansible_password }}"
     register: le_private_key


   - name: 03 - Read The Cloudflare API Key from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "cloudflare_token"
      auth_method: token
      token: "{{ ansible_password }}"
     register: cloudflare_token


#   - name: Print 
#     ansible.builtin.debug:
#       msg: "{{ cloudflare_token.data.data.api_key }}"


   - name: 04 - Generate an OpenSSL Certificate Signing Request
     community.crypto.openssl_csr:
       path: "{{ fqdn }}.csr"
       privatekey_content: "{{ server_private_key.secret.private_key }}"
       common_name: "{{ fqdn }}"


   - name: 05 - Create an ACME Challenge
     community.crypto.acme_certificate:
       account_email: "{{ le_email }}"
       account_key_content: "{{ le_private_key.secret.private_key }}"
       csr: "{{ fqdn }}.csr"
       cert: "{{ fqdn }}.cer"
       chain: "{{ fqdn }}.chain"
       fullchain: "{{ fqdn }}.fullchain"
       challenge: dns-01
       acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
       acme_version: 2
       # Renew if the certificate is at least 30 days old
       remaining_days: 60
     register: challenge_response


#   - name: 0a - Print
#     ansible.builtin.debug:
#       msg: "{{ challenge_response }}"


#  Change this from msg to var
#   - name: 0a1 - Print
#     ansible.builtin.debug:
#       msg: "{{ challenge_response }}"


#   - name: 06 - Extract DNS-01 challenge resource_value
#     ansible.builtin.set_fact:
#       dns_01_challenge_text: "{{ challenge_response.challenge_data['test-csr.theglens.net']['dns-01'].resource_value }}"


#   - name: Print
#     ansible.builtin.debug:
#       msg: "DNS-01 resource_value is: {{ dns_01_challenge_text }}"


   - name: 06 - Extract FQDN and DNS Challenge Text from ACME Response
     ansible.builtin.set_fact:
       dns_01_challenge_text: "{{ challenge_response.challenge_data[fqdn]['dns-01'].resource_value }}"
       dns_01_challenge_fqdn: "{{ challenge_response.challenge_data[fqdn]['dns-01'].record.split('.')[0:2] | join('.') }}"


   - name: 07 - Create DNS TXT record with value "unique value"
     community.general.cloudflare_dns:
       api_token: "{{ cloudflare_token.data.data.api_key }}"
       record: "{{ dns_01_challenge_fqdn }}"
       type: TXT
       value: "{{ dns_01_challenge_text }}"
       state: present    # present (default), absent
       zone: theglens.net
     register: cloudflare_dns_create


   - name: 08 - Pause the Playbook for 20 seconds
     ansible.builtin.pause:
       seconds: 20


   - name: 09 - Let the ACME Challenge be Validated and retrieve the cert and intermediate certificate
     community.crypto.acme_certificate:
       account_email: "{{ le_email }}"
       account_key_content: "{{ le_private_key.secret.private_key }}"
       csr: "{{ fqdn }}.csr"
       cert: "{{ fqdn }}.cer"
       chain: "{{ fqdn }}.chain"
       fullchain: "{{ fqdn }}.fullchain"
       challenge: dns-01
       acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
       acme_version: 2
       # Renew if the certificate is at least 30 days old
       remaining_days: 60
       data: "{{ challenge_response }}"
     register: certificate_response
#     when: sample_com_challenge is changed


#   - name: cat the cert file
#     ansible.builtin.shell: cat "{{ fqdn }}.cer"
#     register: cert_file


   - name: 10 - Delete the DNS TXT record (if it exists)
     community.general.cloudflare_dns:
       api_token: "{{ cloudflare_token.data.data.api_key }}"
       record: "{{ dns_01_challenge_fqdn }}"
       type: TXT
#       value: "{{ dns_01_challenge_text }}"
       state: absent    # present (default), absent
       zone: theglens.net
#     register: cloudflare_dns_delete


   - name: 11 - Write the New Certificate to Vault
     community.hashi_vault.vault_kv2_write:
       url: "{{ vault_url }}"
       engine_mount_point: "{{ vault_mount }}"
       path: "{{ fqdn }}"
       data:
         cert: "{{ lookup('file', '{{ fqdn }}.cer') }}"
         chain: "{{ lookup('file', '{{ fqdn }}.chain') }}"
         fullchain: "{{ lookup('file',  '{{ fqdn }}.fullchain') }}"
       auth_method: token
       token: "{{ ansible_password }}"





   - name: 12 - Read the New Certificate from Vault, REQD for the next step 
     community.hashi_vault.vault_kv2_get:
       url: "{{ vault_url }}"
       engine_mount_point: "{{ vault_mount }}"
       path: "{{ fqdn }}"
       auth_method: token
       token: "{{ ansible_password }}"
     register: current


   - name: 13 - Append the Public Key to Vault Secret
     vars:
       values_to_update:
          fullchain: "{{ lookup('file',  '{{ fqdn }}.fullchain') }}"
     community.hashi_vault.vault_kv2_write:
       url: "{{ vault_url }}"
       engine_mount_point: "{{ vault_mount }}"
       path: "{{ fqdn }}"
       data: >-
         {{
           current.secret
           | combine(values_to_update)
         }}
       auth_method: token
       token: "{{ ansible_password }}"









#   - name: 04b - Display challenge_data_dns
#     ansible.builtin.debug:
#       var: challenge_response.challenge_data_dns
#
#   - name: 04c - Extract TXT record hostname (_acme-challenge.test-csr)
#     set_fact:
#       txt_record_hostname: "{{ item.split('.')[0] }}.{{ item.split('.')[1] }}"
#     vars:
#       item: "{{ challenge_response.challenge_data_dns.keys() | first }}"
#
#
#   - name: 04d - Print
#     ansible.builtin.debug:
#       msg: "{{ txt_record_hostname }}"
#
#   - name: 04e - Print
#     ansible.builtin.debug:
#       msg: "{{ txt_record_hostname }}"



   - name: Create TXT record with value "unique value"
     community.general.cloudflare_dns:
       api_token: "{{ cloudflare_token.secret.api_token }}"
       record: testansible
       type: TXT
       value: this-is-a-unique-value
       state: present    # present (default), absent
       zone: theglens.net
     register: cloudflare_response




   - name: Print the DNS-01 resource value
     ansible.builtin.debug:
       msg: "{{ challenge_response['msg']['challenge_data_dns'] }}"









   - name: Create TXT record with value "unique value"
     community.general.cloudflare_dns:
       api_token: "{{ cloudflare_token.secret.api_token }}"
       record: testansible
       type: TXT
       value: this-is-a-unique-value
       state: present    # present (default), absent
       zone: theglens.net
     register: cloudflare_response

   - name: Print 
     ansible.builtin.debug:
       msg: "{{ challenge_response }}"






#   - name: Print 
#     ansible.builtin.debug:
#       msg: "{{ response.secret.public_key }}"
#       msg: "{{ response.secret.private_key }}"
