---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Query IP geolocation API using ansible.builtin.uri
      ansible.builtin.uri:
        url: "https://api.ipgeolocation.io/ipgeo?apiKey={{ ansible_password }}&ip=ssl-vpn.theglens.net"
        method: GET
        return_content: true
      register: ip_geo_result

    - name: Print the geolocation result
      ansible.builtin.debug:
        var: ip_geo_result.content

    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play

