---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"

  tasks:

   - name: 01 - Read The Servers Private Key from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "ssl_vpn_theglens_net_keys"
      auth_method: token
      token: "{{ ansible_password }}"
     register: response

    - name: Print 
      ansible.builtin.debug:
        msg: "{{ response.secret.public_key }}"
        msg: "{{ response.secret.private_key }}"

   - name: Timmay HARD STOP this Playbook
     ansible.builtin.meta: end_play




   - name: Generate an OpenSSL Certificate Signing Request
     community.crypto.openssl_csr:
       path: /etc/ssl/csr/www.ansible.com.csr
       privatekey_path: /etc/ssl/private/ansible.com.pem
       common_name: test-csr.theglens.net

