---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate an OpenSSL private key with the default values (4096 bits, RSA) and a passphrase
      community.crypto.openssl_privatekey:
        path: "~/le-account.key"

    - name: Create ACME account
      community.crypto.acme_account:
        account_key_src: "~/le-account.key"
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_version: 2
        contact:
          - mailto:timmayglen@gmail.com
        state: present
        terms_agreed: true
      register: acme_account

    - name: Display ACME account details
      ansible.builtin.debug:
        var: acme_account

    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play
