---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Query Google DNS for ssl-vpn.theglens.net
      ansible.builtin.uri:
        url: "https://dns.google/resolve?name=ssl-vpn.theglens.net&type=a&do=1"
        method: GET
        return_content: true
      register: dns_result

    - name: Set the IP address from DNS response as a fact
      ansible.builtin.set_fact:
        ip_address: "{{ dns_result.content.Answer[0].data }}"

    - name: Print the extracted IP address
      ansible.builtin.debug:
        var: ip_address


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play

