---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost
  gather_facts: false
  tasks:

    - name: 01 - Check whether an account with the given account key exists
      community.crypto.acme_account_info:
        account_key_src: "~/le-account.key"
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_version: 2
      register: account_data

    - name: 02 - Verify that account exists
      ansible.builtin.assert:
        that:
          - account_data.exists

    - name: 03 - Print account URI
      ansible.builtin.debug:
        var: account_data.account_uri

    - name: 04 - Print account contacts
      ansible.builtin.debug:
        var: account_data.account.contact

    - name: 05 - Check whether the account exists and is accessible with the given account key
      acme_account_info:
        account_key_content: "{{ acme_account_key }}"
        account_uri: "{{ acme_account_uri }}"
      register: account_data

    - name: 06 - Verify that account exists
      ansible.builtin.assert:
        that:
          - account_data.exists

    - name: 07 - Print account contacts
      ansible.builtin.debug:
        var: account_data.account.contact


