---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  tasks:



    - name: Create TXT record with value "unique value"
      community.general.cloudflare_dns:
        api_token: "{{ ansible_password }}"
        record: testansible
        type: TXT
        value: this-is-a-unique-value
        state: present    # present (default), absent
        zone: theglens.net
      register: response



    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play


