---
- name: Tasks in this Playbook are for testing purposes only
  hosts: localhost
  gather_facts: false
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"
   vault_secret: "homenet_inet_ip"



    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play


