---
- name: Create \ Renew a Certificate using ACME and Store it in Vault
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Print the name of the FQDN
      ansible.builtin.debug:
        msg: "The fqdn for this certificate will be {{ fqdn }}."


    - name: 01 - Read existing certificate from Vault
      community.hashi_vault.vault_kv2_get:
        path: "{{ fqdn }}"
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method }}"
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
        version: "{{ vault_kv_version | default(omit) }}"
      register: vault_cert
      failed_when: false
      changed_when: false



    - name: 02 - Retrieve renewal information for a certificate
      community.crypto.acme_certificate_renewal_info:
        acme_directory: "{{ acme_directory }}"
        acme_version: 2
        certificate_content: "{{ vault_cert.data.data.cert }}"
        use_ari: true
        # now: "{{ now_time }}"
      register: cert_data


    - name: 03 - Should the certificate be renewed?
      ansible.builtin.debug:
        var: cert_data.should_renew



    - name: 0c - Get ARI renewal info
      community.crypto.acme_ari_info:
        acme_directory: "{{ acme_directory }}"
        acme_version: 2
        certificate_content: "{{ vault_cert.data.data.cert }}"
      register: ari_info

    - name: 0d - Is the ARI Renewal Time Window Open
      ansible.builtin.set_fact:
        now_utc: "{{ ansible_date_time.iso8601 }}"
        allow_renewal: "{{ ansible_date_time.iso8601 >= ari_info.renewal_info.suggestedWindow.start }}"


    - name: 0e - Print ARI timing and renewal decision
      ansible.builtin.debug:
        msg:
          - "Current time (UTC): {{ now_utc }}"
          - "ARI window start:   {{ ari_info.renewal_info.suggestedWindow.start }}"
          - "ARI window end:     {{ ari_info.renewal_info.suggestedWindow.end }}"
          - "Allow renewal:      {{ allow_renewal }}"
