---
- name: Create \ Renew a Certificate using ACME and Store it in Vault
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Print Github Debugging Info
      ansible.builtin.debug:
        msg: "This is NOT a PROD file, this is part of the Github branch  feature/acme-ari."

    - name: Print the name of the FQDN
      ansible.builtin.debug:
        msg: "The fqdn for this certificate will be {{ fqdn }}."


    - name: 0a - Attempt to read existing certificate from Vault
      community.hashi_vault.vault_kv2_get:
        path: "{{ fqdn }}"
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method }}"
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
        version: "{{ vault_kv_version | default(omit) }}"        
      register: vault_cert
      failed_when: false
      changed_when: false


    - name: Set certificate metadata version
      ansible.builtin.set_fact:
        cert_metadata_version: "{{ vault_cert.raw.data.metadata.version }}"

    # That guarantees the playbook won’t blow up if:
    #  the secret is new
    #  the path doesn’t exist
    #  metadata is missing

    - name: Set certificate metadata version (safe)
      ansible.builtin.set_fact:
        cert_metadata_version: "{{ vault_cert.raw.data.metadata.version | default(0) }}"



    - name: Set previous certificate metadata version
      ansible.builtin.set_fact:
        previous_cert_metadata_version: "{{ cert_metadata_version | int - 1 }}"

    # This assures we will nevr end up with -1 on a brand-new secret

    - name: Set previous certificate metadata version (safe)
      ansible.builtin.set_fact:
        previous_cert_metadata_version: >-
          {{ (cert_metadata_version | int - 1) if (cert_metadata_version | int) > 0 else 0 }}

