---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Generate an RSA Private Key
      community.crypto.openssl_privatekey:
        path: "~/private.key"
        size: 2048

    - name: Write the Private Key to Vault
      community.hashi_vault.vault_kv2_write:
        url: "https://vault.theglens.net:8200"
        engine_mount_point: "kv"
        path: "le_stage_key/private"
        data:
          private_key: "{{ lookup('file', '~/private.key') }}"
        auth_method: token
        token: "{{ ansible_password }}"

    - name: Stop the playbook
      ansible.builtin.meta: end_play
 

    - name: Extract public key
      community.crypto.openssl_publickey:
        privatekey_path: ~/private.key
        path: ~/public.key

    - name: Write the Public Key to Vault
      community.hashi_vault.vault_kv2_write:
        url: "https://vault.theglens.net:8200"
        mount_point: "kv"
        path: "le_stage_key/public"
        data:
          public_key: "{{ lookup('file', '~/public.key') }}"
        auth_method: token
        token: "{{ ansible_password }}"
