---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure the local directory exists
      ansible.builtin.file:
        path: "/var/lib/awx/projects/local"
        state: directory
        mode: '0755'

    - name: Generate an RSA Private Key
      community.crypto.openssl_privatekey:
        path: "/var/lib/awx/projects/local/private.key"

