---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Generate an RSA Private Key
      community.crypto.openssl_privatekey:
        path: "~/private.key"

    - name: Extract public key
      community.crypto.openssl_publickey:
        privatekey_path: ~/private.key
        path: ~/public.key

    - name: Stop the playbook
      meta: end_play

    - name: Ensure the local directory exists
      ansible.builtin.file:
        path: "/var/lib/awx/projects/local"
        state: directory
        mode: '0755'

