---
- name: Create a PKCS12 File from a Certificate and Key
  hosts: localhost
  gather_facts: false
  vars:
    ssl_cert_fqdn: aaajsnlb.theglens.net

  tasks:

    - name: 01 - Obtain the Private Key from Vault
      community.hashi_vault.vault_kv2_get:
        url: "https://vault.theglens.net:8200"
        path: "generic_use_ec384_keys"
        auth_method: token
        token: "{{ ansible_password }}"
        engine_mount_point: "kv"
      register: private_key


    - name: 02 - Write the Private Key to a file
      ansible.builtin.copy:
        content: "{{ private_key.data.data.private_key }}"
        dest: "private_key.pem"
        mode: 0600


    - name: 03 - Obtain the Full Chain from Vault
      community.hashi_vault.vault_kv2_get:
        url: "https://vault.theglens.net:8200"
        path: "{{ ssl_cert_fqdn }}"
        auth_method: token
        token: "{{ ansible_password }}"
        engine_mount_point: "kv"
      register: full_chain

    - name: 04 - Write the Full Chain to a file
      ansible.builtin.copy:
        content: "{{ full_chain.data.data.fullchain }}"
        dest: "fullchain.pem"
        mode: 0600


    - name: 05 - Create the binary PKCS12 File using Community Crypto OpenSSL_Pkcs12
      community.crypto.openssl_pkcs12:
        action: export
        friendly_name: "{{ ssl_cert_fqdn }}"
        passphrase: "cisco123"
        path: pkcs12_file.p12
        privatekey_path : private_key.pem
        certificate_path : fullchain.pem
        state: present

    - name: 06 - Encode the PKCS12 file to base64
      ansible.builtin.command:
        cmd: "base64 pkcs12_file.p12 -o pkcs12_file_base64.txt"
      args:
        removes: pkcs12_file.p12

    - name: 07 - Display the base64-encoded PKCS12 file
      ansible.builtin.debug:
        msg: "{{ lookup('file', 'pkcs12_file_base64.txt') }}"


    - name: 06 - Run a Command on the local linux host
      ansible.builtin.command: "ls -l"
      register: command_output


    - name: 07 - Run a Command on the local linux host
      ansible.builtin.command: "openssl pkcs12 -in pkcs12_file.p12 -info -nodes -passin pass:cisco123"
      register: command_output


    - name: TIMMAY Stop the Playbool
      ansible.builtin.meta: end_play


