---
- name: Create a PKCS12 File from a Certificate and Key
  hosts: localhost
  gather_facts: false
  tasks:

  vars:
    ssl_cert_fqdn: "lab-ftd.theglens.net"

    - name: 01 - Obtain the Private Key from Vault
      community.hashi_vault.vault_kv2_get:
        url: "https://vault.theglens.net:8200"
        path: "generic_use_ec384_keys"
        auth_method: token
        token: "{{ ansible_password }}"
        engine_mount_point: "kv"
      register: private_key


    - name: 02 - Write the Private Key to a file
      ansible.builtin.copy:
        content: "{{ private_key.data.data.private_key }}"
        dest: "private_key.pem"
        mode: 0600


    - name: 03 - Obtain the Full Chain from Vault
      community.hashi_vault.vault_kv2_get:
        url: "https://vault.theglens.net:8200"
        path: "{{ ssl_cert_fqdn }}"
        auth_method: token
        token: "{{ ansible_password }}"
        engine_mount_point: "kv"
      register: full_chain

    - name: 04 - Write the Full Chain to a file
      ansible.builtin.copy:
        content: "{{ full_chain.data.data.fullchain }}"
        dest: "fullchain.pem"
        mode: 0600


    - name: 05 - Create the PKCS12 File using Community Crypto OpenSSL_Pkcs12
      community.crypto.openssl_pkcs12:
        action: export
        friendly_name: "{{ ssl_cert_fqdn }}"
        passphrase: "cisco123"
        privatekey_passphrase : "cisco123"
        path: pkcs12_file.p12
        privatekey_path : private_key.pem
        certificate_path : fullchain.pem
        state: present




    - name: TIMMAY Stop the Playbool
      ansible.builtin.meta: end_play


